#!/usr/bin/env bash
. "$(dirname "$0")/_/husky.sh"

# Check if all strings are translated in all languages
check_translations() {
  cd play || exit 1
  npm run i18n:check
}

(
cd play || exit
npm run precommit
)
#(
#check_translations
#)
(
check_translations
)
(
cd tests || exit
npm run precommit
)
(
cd libs/map-editor || exit
npm run precommit
)
(
cd libs/shared-utils || exit
npm run precommit
)
(
cd libs/store-utils || exit
npm run precommit
)
